name: StaticAnalysis

on:
  push:
    branches:
      - workflow-test

jobs:
  code-ql:
    runs-on: ubuntu-20.04

    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false

      matrix:
        language: [ 'cpp' ]

        compiler:
          - 'clang-14'

        build_type:
          - 'Release'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.os }}-${{ matrix.compiler }}

      - name: Setup Environment
        run: scripts/ci/SetupEnvironment.sh

      - name: Install compiler
        run: scripts/ci/InstallTools.sh ${{ matrix.compiler }} ninja

      - name: Configure build directory
        run: |
          mkdir build -p
          cd build

          cmake -DCMAKE_BUILD_TYPE:STRING=${{ matrix.build_type }} -DPHI_TEST_WITH_ALL_STANDARDS:BOOL=OFF -DPHI_COVERAGE_BUILD:BOOL=${{ matrix.build_type == 'Debug' }} ..

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        # Override language selection by uncommenting this and choosing your languages
        with:
          languages: ${{ matrix.language }}
          debug: true
          # If you wish to specify custom queries, you can do so here or in a config file.
          # By default, queries listed here will override any specified in a config file.
          # Prefix the list here with "+" to use these queries and those in the config file.
          # queries: ./path/to/local/query, your-org/your-repo/queries@main

      - name: Build
        working-directory: ./build
        run: cmake --build . --config ${{ matrix.build_type }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
